version: '3.8'
services:
  neo4j:
    image: neo4j:2025.02.0-community
    container_name: neo4j
    restart: always
    ports:
      - '7687:7687'
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/var/lib/neo4j/data

volumes:
  neo4j_data:
