{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secrets.name }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
type: Opaque
data:
  # Здесь будут закодированные в base64 секреты, переданные через переменные .Values.secrets.data
  {{- if .Values.secrets.data }}
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }} 