/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ReputationStorage {
  export type MarkStruct = {
    fromParticipantId: BigNumberish;
    toParticipantId: BigNumberish;
    value: boolean;
    markType: string;
  };

  export type MarkStructOutput = [
    fromParticipantId: bigint,
    toParticipantId: bigint,
    value: boolean,
    markType: string
  ] & {
    fromParticipantId: bigint;
    toParticipantId: bigint;
    value: boolean;
    markType: string;
  };
}

export interface ReputationStorageInterface extends Interface {
  getFunction(
    nameOrSignature: "getMark" | "getMarksCount" | "marks" | "storeMark"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MarkStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMark",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarksCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "marks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "storeMark",
    values: [BigNumberish, BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(functionFragment: "getMark", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarksCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storeMark", data: BytesLike): Result;
}

export namespace MarkStoredEvent {
  export type InputTuple = [
    sender: AddressLike,
    fromParticipantId: BigNumberish,
    toParticipantId: BigNumberish,
    value: boolean,
    markType: string
  ];
  export type OutputTuple = [
    sender: string,
    fromParticipantId: bigint,
    toParticipantId: bigint,
    value: boolean,
    markType: string
  ];
  export interface OutputObject {
    sender: string;
    fromParticipantId: bigint;
    toParticipantId: bigint;
    value: boolean;
    markType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationStorage extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationStorage;
  waitForDeployment(): Promise<this>;

  interface: ReputationStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMark: TypedContractMethod<
    [index: BigNumberish],
    [ReputationStorage.MarkStructOutput],
    "view"
  >;

  getMarksCount: TypedContractMethod<[], [bigint], "view">;

  marks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, string] & {
        fromParticipantId: bigint;
        toParticipantId: bigint;
        value: boolean;
        markType: string;
      }
    ],
    "view"
  >;

  storeMark: TypedContractMethod<
    [
      fromParticipantId: BigNumberish,
      toParticipantId: BigNumberish,
      value: boolean,
      markType: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMark"
  ): TypedContractMethod<
    [index: BigNumberish],
    [ReputationStorage.MarkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarksCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, string] & {
        fromParticipantId: bigint;
        toParticipantId: bigint;
        value: boolean;
        markType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeMark"
  ): TypedContractMethod<
    [
      fromParticipantId: BigNumberish,
      toParticipantId: BigNumberish,
      value: boolean,
      markType: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MarkStored"
  ): TypedContractEvent<
    MarkStoredEvent.InputTuple,
    MarkStoredEvent.OutputTuple,
    MarkStoredEvent.OutputObject
  >;

  filters: {
    "MarkStored(address,uint256,uint256,bool,string)": TypedContractEvent<
      MarkStoredEvent.InputTuple,
      MarkStoredEvent.OutputTuple,
      MarkStoredEvent.OutputObject
    >;
    MarkStored: TypedContractEvent<
      MarkStoredEvent.InputTuple,
      MarkStoredEvent.OutputTuple,
      MarkStoredEvent.OutputObject
    >;
  };
}
